In [1]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
import os
import math
from sklearn.cluster import KMeans
%matplotlib inline
import sys

In [2]:
sys.path.append("..")
from framework import perspective_transform
from framework import visualize

In [3]:
data_path = "/home/avk/study/1C/Diplom/IlluminationCorrection/SamplesData/"

In [13]:
for file_num, filename in enumerate(os.listdir(data_path)):
    full_file_path = os.path.join(data_path, filename)
    if file_num == 0:
        break
file_num, full_file_path

(0,
 '/home/avk/study/1C/Diplom/IlluminationCorrection/SamplesData/IMG_20190317_170456.jpg')

In [5]:
initial_image = cv2.imread(full_file_path)
# visualize.visualize_image(initial_image)
initial_image.shape

(4032, 3016, 3)

In [6]:
img = initial_image

In [7]:
visualize.visualize_image(img)

In [8]:
#-----Converting image to LAB Color model----------------------------------- 
lab= cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
# visualize.visualize_image(lab)

In [9]:
#-----Splitting the LAB image to different channels-------------------------
l, a, b = cv2.split(lab)
visualize.visualize_image(l, 'l_channel')
# visualize.visualize_image(a, 'a_channel')
# visualize.visualize_image(b, 'b_channel')
# l.fill(l.mean())
l = np.rint((l - l.mean()) / 10 + l.mean()).astype(np.uint8)
print(l)

[[150 150 150 ... 148 149 148]
 [150 150 150 ... 148 148 148]
 [150 150 149 ... 148 148 148]
 ...
 [146 146 146 ... 156 156 156]
 [146 146 146 ... 156 156 156]
 [146 146 146 ... 156 156 156]]


In [10]:
#-----Applying CLAHE to L-channel-------------------------------------------
# clahe = cv2.createCLAHE(clipLimit=5, tileGridSize=(8,8))
# cl = clahe.apply(l)
# cl = l
cl = cv2.equalizeHist(l)
visualize.visualize_image(cl, 'CLAHE output ')

In [11]:
#-----Merge the CLAHE enhanced L-channel with the a and b channel-----------
limg = cv2.merge((cl, a, b))
# visualize.visualize_image(limg, 'limg ')

In [12]:
#-----Converting image from LAB Color model to RGB model--------------------
final = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)
visualize.visualize_image(final, 'final ')