In [1]:
import numpy as np
import cv2
from matplotlib import pyplot as plt
import os
import math
from sklearn.cluster import KMeans
%matplotlib inline
import sys

In [2]:
sys.path.append("..")
from framework import perspective_transform
from framework import visualize

In [3]:
# data_path = "/home/avk/study/1C/Diplom/IlluminationCorrection/SamplesData/"

In [4]:
# for file_num, filename in enumerate(os.listdir(data_path)):
#     full_file_path = os.path.join(data_path, filename)
#     if file_num == 0:
#         break
# file_num, full_file_path

In [5]:
full_file_path = "/home/avk/study/1C/Diplom/Pandore/pandore1/bin/experiments/examples/example4/0.jpg"

In [6]:
initial_image = cv2.imread(full_file_path)
visualize.visualize_image(initial_image)
initial_image.shape

(4393, 2864, 3)

In [7]:
image_hls = cv2.cvtColor(initial_image, cv2.COLOR_BGR2HLS)
lightness = image_hls[:,:,1]
visualize.visualize_image(lightness)

In [8]:
np.min(lightness), np.max(lightness), np.mean(lightness)

(26, 238, 180.676189233252)

In [9]:
print(lightness)

[[113 114 120 ... 166 166 166]
 [134 134 138 ... 166 166 166]
 [155 155 158 ... 166 166 165]
 ...
 [ 98  98  98 ... 192 192 190]
 [ 98  98 100 ... 193 193 190]
 [ 96  98 100 ... 191 189 190]]


In [10]:
kernel = np.ones((11, 11), np.uint8)
dilatation = cv2.dilate(lightness, kernel, iterations=1) 
visualize.visualize_image(dilatation)

In [11]:
erosion = cv2.erode(dilatation, kernel, iterations=1)
visualize.visualize_image(erosion)

In [12]:
np.min(erosion), np.max(erosion), np.mean(erosion)

(63, 238, 190.98878858506487)

In [13]:
print(erosion)

[[174 174 174 ... 166 166 166]
 [174 174 174 ... 166 166 166]
 [174 174 174 ... 166 166 166]
 ...
 [102 102 102 ... 193 194 194]
 [102 102 102 ... 193 194 194]
 [102 102 102 ... 193 194 194]]


In [17]:
result = np.array(lightness, dtype=np.int16) - np.array(erosion, dtype=np.int16) + int(np.mean(erosion))
result = result - np.mean(result) + np.mean(lightness)
result = np.array(np.clip(result, 0, 255), dtype=np.uint8)
print(np.min(result), np.max(result), np.mean(result))
print(result)

28 190 179.68740064818712
[[129 130 136 ... 190 190 190]
 [150 150 154 ... 190 190 190]
 [171 171 174 ... 190 190 189]
 ...
 [186 186 186 ... 189 188 186]
 [186 186 188 ... 190 189 186]
 [184 186 188 ... 188 185 186]]


In [18]:
np.min(result), np.max(result), np.mean(result)

(28, 190, 179.68740064818712)

In [19]:
visualize.visualize_image(result)
# result = 255 / (np.max(result) - np.min(result)) * (result - np.min(result))
restored = image_hls.copy()
restored[:,:,1] = result
restored = cv2.cvtColor(restored, cv2.COLOR_HLS2BGR)
visualize.visualize_image(restored)