In [1]:
import numpy as np
import perspective_transform
import cv2

In [5]:
def order_points(pts):
    # initialize a list of coordinates that will be ordered
    # such that the first entry in the list is the top-left,
    # the second entry is the top-right, the third is the
    # bottom-right, and the fourth is the bottom-left
    rect = np.zeros((4, 2), dtype="float32")

    # the top-left point will have the smallest sum, whereas
    # the bottom-right point will have the largest sum
    s = pts.sum(axis=1)
    rect[0] = pts[np.argmin(s)]
    rect[2] = pts[np.argmax(s)]

    # now, compute the difference between the points, the
    # top-right point will have the smallest difference,
    # whereas the bottom-left will have the largest difference
    diff = np.diff(pts, axis=1)
    rect[1] = pts[np.argmin(diff)]
    rect[3] = pts[np.argmax(diff)]

    # return the ordered coordinates
    return rect

In [2]:
a = np.array([0, 0, 1, 0, 1, 1, 0, 1]).reshape((4, 2))
a

array([[0, 0],
       [1, 0],
       [1, 1],
       [0, 1]])

In [6]:
sorted_points = perspective_transform.order_points(a)
sorted_points

array([[0, 1],
       [1, 1],
       [1, 0],
       [0, 0]])

In [7]:
order_points(a)

array([[0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 1.]], dtype=float32)

In [4]:
cv2.getPerspectiveTransform()

TypeError: getPerspectiveTransform() missing required argument 'src' (pos 1)